[package]
name = "fastside"
description = "A smart redirecting gateway for various frontend services."
version = "0.2.0"
edition.workspace = true
rust-version.workspace = true
default-run = "fastside"

[features]
default = ["native"]
native = [
  "axum/http1",
  "axum/http2",
  "axum/tokio",
  "dep:anyhow",
  "dep:clap",
  "dep:reqwest",
  "dep:redis",
  "dep:sqlx",
  "fastside-shared/native",
  "reqwest/http2",
  "reqwest/rustls",
  "reqwest/socks",
  "tokio/fs",
  "tokio/macros",
  "tokio/net",
  "tokio/rt-multi-thread",
  "tokio/signal",
  "tokio/time",
]

[dependencies]
fastside-shared = { path = "../fastside-shared", default-features = false }

anyhow = { workspace = true, optional = true }
askama.workspace = true
async-trait.workspace = true
axum.workspace = true
chrono.workspace = true
clap = { workspace = true, optional = true }
cookie.workspace = true
fastrand.workspace = true
futures.workspace = true
getrandom.workspace = true
ipnet.workspace = true
log.workspace = true
regex.workspace = true
reqwest = { workspace = true, optional = true }
redis = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
sqlx = { workspace = true, optional = true }
thiserror.workspace = true
time.workspace = true
tokio = { workspace = true, features = ["sync"] }
url.workspace = true
urlencoding.workspace = true

[dev-dependencies]
tower-service.workspace = true

[[bin]]
name = "fastside"
path = "src/main.rs"
required-features = ["native"]
