[workspace]
members = ["fastside", "fastside-actualizer", "fastside-shared"]
resolver = "2"

[profile.release]
overflow-checks = true
incremental = false
codegen-units = 1
opt-level = 3
debug = "full"
strip = true
lto = true
