[package]
name = "fastside-shared"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[features]
default = ["native"]
native = [
  "dep:anyhow",
  "dep:config",
  "dep:log",
  "dep:pretty_env_logger",
  "dep:reqwest",
  "dep:tokio",
  "reqwest/http2",
  "reqwest/rustls",
  "reqwest/socks",
  "tokio/macros",
  "tokio/rt-multi-thread",
  "tokio/time",
]

[dependencies]
anyhow = { workspace = true, optional = true }
base64ct.workspace = true
config = { workspace = true, optional = true }
log = { workspace = true, optional = true }
pretty_env_logger = { workspace = true, optional = true }
regex.workspace = true
reqwest = { workspace = true, optional = true }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["sync"], optional = true }
url.workspace = true
